version: "3.7"

services:
  topkartapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c  "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000 &&
              python manage.py crontab add &&
              gunicorn topkart.wsgi:application --bind=0.0.0.0:8000"
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - topkartapi_network

networks:
  topkartapi_network:
    driver: bridge